#!/usr/bin/env bash

__datadir=$HOME/.contextual

__context=${__context:-'main'}

__timeline=

__puton__ () {
  mkdir -p $__datadir/contexts
  __timeline=$__datadir/timeline
}

path__help='@arg (optional) context @does print path to datadir for the provided context or the current context'
path__ () {
  local context=${1:-$CONTEXT}
  echo $__datadir/contexts/$context
}

install__help='@does install the app by enabling potato toppings'
install__ () {
  local basedir=$(dirname $__src__)
  cd $basedir/toppings
  for file in *; do
    __exec potato enable $file
  done
}

timeline__ () {
  cat $__timeline
}

notes__help='@does open notes for this context'
notes__ () {
  ${EDITOR:-vim} $CONTEXT_PATH/notes
}

recent__help='@does list recent contexts from the newsest first'
recent__ () {
  timeline__ | cut -d$'\t' -f2 | xargs -I {} basename {} | awk '!x[$0]++' | tac
}

list__help='@does list domains or contexts under the set domain.'
list__ () {
 ls $__datadir/${__domain}
}

domains__help='@does list all domains.'
domains__ () {
 ls $__datadir 
}

tree__help='@does print a tree of all contexts under their domain'
tree__ () {
 tree -d $__datadir
}

dirs__help='@does list dirs visited in this context.'
dirs__ () {
  cat $CONTEXT_PATH/pwd | uniq | sort | tee $CONTEXT_PATH/pwd
}

which__help='@arg dir @does list contexts in which dir exists'
which__ () {
  local path=$(realpath ${1:-$(pwd)})
  find $__datadir -name pwd -exec grep $path -H {} \; | sed "s|$__datadir\/\(.*\)\/pwd.*|\1|" | uniq
}

info__help='@does provide info on current context'
info__ () {
  find $CONTEXT_PATH -type f
}

source undies
